name: Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/test.yaml'
      - 'chronos_file.nim*'
      - 'chronos_file/**'
      - 'tests/**'
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - 'chronos_file.nim*'
      - 'chronos_file/**'
      - 'tests/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'macOS-latest'
        nim-version:
          - '2.0.16'
          - 'stable'
          - 'devel'

    steps:
    - uses: actions/checkout@v6

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v5
      with:
        path: ~/.nimble
        key: unit-tests-nimble-v2-${{ matrix.os }}-${{ matrix.nim-version }}-${{ github.sha }}
        restore-keys: |
          unit-tests-nimble-v2-${{ matrix.os }}-${{ matrix.nim-version }}-

    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      if: matrix.nim-version != 'devel'

    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-version }}
        use-nightlies: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      if: matrix.nim-version == 'devel'

    - name: Run unit test
      run: |
        nimble test -y

  test-uring:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nim-version:
          - '2.0.16'
          - 'stable'
          - 'devel'

    steps:
    - uses: actions/checkout@v6

    - name: Cache nimble
      uses: actions/cache@v5
      with:
        path: ~/.nimble
        key: uring-tests-nimble-v1-${{ matrix.nim-version }}-${{ github.sha }}
        restore-keys: |
          uring-tests-nimble-v1-${{ matrix.nim-version }}-

    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install iori
      run: nimble install iori

    - name: Run unit tests
      run: nimble test -y

    - name: Run io_uring unit tests
      run: nimble testUring -y
